# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45ea88d81cb589205efa203d922077cb6bd4b0e7f01c6f45dd5737dd78d7b3dafd229571a7a1fcf139c7594e68e2540dc444c2699357c73a241bc013b02c1161

test:
  secret_key_base: a0b8d8edf091daf835c0b436c91a52cdd1cc806801196ab7a1d2f5d7c26eb33996df221de30fc6acd0b0565bc3328871079fe7a1e71b9f57c4f904b5f64085f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
